ALTER TABLE "DocumentCategory"
  ADD COLUMN IF NOT EXISTS "kind" TEXT NOT NULL DEFAULT 'PERSONAL',
  ADD COLUMN IF NOT EXISTS "scopes" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "rules" JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "uploadRoles" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "viewRoles" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "approvalRoles" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "externalLinks" JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "notes" TEXT;
