import { Router } from "express";
import { auditRouter } from "./modules/audit/audit.routes";
import { auditParametersRouter } from "./modules/audit-parameters/auditParameters.routes";
import { authRouter } from "./modules/auth/auth.routes";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes";
import { documentCategoriesRouter } from "./modules/document-categories/documentCategories.routes";
import { documentsRouter } from "./modules/documents/documents.routes";
import { employeesRouter } from "./modules/employees/employees.routes";
import { finnegansExportRouter } from "./modules/finnegans-export/finnegansExport.routes";
import { healthRouter } from "./modules/health/health.routes";
import { hourConceptsRouter } from "./modules/hour-concepts/hourConcepts.routes";
import { noveltyTypesRouter } from "./modules/novelty-types/noveltyTypes.routes";
import { noveltiesRouter } from "./modules/novelties/novelties.routes";
import { orgStructureRouter } from "./modules/org-structure/orgStructure.routes";
import { pendingRouter } from "./modules/pending/pending.routes";
import { positionsRouter } from "./modules/positions/positions.routes";
import { salaryCategoriesRouter } from "./modules/salary-categories/salaryCategories.routes";
import { storageRouter } from "./modules/storage/storage.routes";
import { timeEntriesRouter } from "./modules/time-entries/timeEntries.routes";
import { usersRouter } from "./modules/users/users.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/audit", auditRouter);
apiRouter.use("/audit-parameters", auditParametersRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/document-categories", documentCategoriesRouter);
apiRouter.use("/documents", documentsRouter);
apiRouter.use("/employees", employeesRouter);
apiRouter.use("/finnegans-export", finnegansExportRouter);
apiRouter.use("/health", healthRouter);
apiRouter.use("/hour-concepts", hourConceptsRouter);
apiRouter.use("/novelty-types", noveltyTypesRouter);
apiRouter.use("/novelties", noveltiesRouter);
apiRouter.use("/org-structure", orgStructureRouter);
apiRouter.use("/pending", pendingRouter);
apiRouter.use("/positions", positionsRouter);
apiRouter.use("/salary-categories", salaryCategoriesRouter);
apiRouter.use("/storage", storageRouter);
apiRouter.use("/time-entries", timeEntriesRouter);
apiRouter.use("/users", usersRouter);
