import { useEffect, useState, type FormEvent } from "react";
import { Pencil, Plus, Power, Trash2, X } from "lucide-react";
import { PageHeader } from "../components/ui/PageHeader";
import { Section } from "../components/ui/Section";
import { Button } from "../components/ui/Button";
import { LoadingState } from "../components/ui/LoadingState";
import { workforceApiService, type DoubleHourRule, type ShiftTemplate } from "../services/api/workforceApiService";
import type { Employee } from "../types";
import { confirmAction } from "../services/appDialog";
import { EmployeeRemoteSelector } from "../components/employees/EmployeeRemoteSelector";

export function WorkScheduleSettingsPage() {
  const [templates, setTemplates] = useState<ShiftTemplate[]>([]); const [rules, setRules] = useState<DoubleHourRule[]>([]); const [selectedRuleEmployees, setSelectedRuleEmployees] = useState<Employee[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(false); const [isLoading, setIsLoading] = useState(true);
  const [shift, setShift] = useState({ code: "", name: "", startTime: "07:00", endTime: "15:00", entryToleranceMinutes: 10, exitToleranceMinutes: 20, detectionWindowMinutes: 180, status: "ACTIVO" });
  const [editingShiftId, setEditingShiftId] = useState<string>();
  const [rule, setRule] = useState({ name: "", recurrenceType: "FECHA" as "FECHA" | "RANGO" | "SEMANAL", fromDate: "", toDate: "", weekdays: [] as number[], multiplier: 2, employeeIds: [] as string[], reason: "" });
  const load = async () => { setIsLoading(true); try { const [a,b] = await Promise.all([workforceApiService.shiftTemplates(), workforceApiService.doubleHourRules()]); setTemplates(a); setRules(b); } catch { setError("No se pudo cargar la configuración horaria."); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const resetShift = () => { setEditingShiftId(undefined); setShift({ code: "", name: "", startTime: "07:00", endTime: "15:00", entryToleranceMinutes: 10, exitToleranceMinutes: 20, detectionWindowMinutes: 180, status: "ACTIVO" }); };
  const submitShift = async (event: FormEvent) => { event.preventDefault(); setWorking(true); setError(""); setNotice(""); try { if (editingShiftId) await workforceApiService.updateShiftTemplate(editingShiftId, shift); else await workforceApiService.createShiftTemplate(shift); setNotice(editingShiftId ? "Turno actualizado correctamente." : "Turno creado correctamente."); resetShift(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar el turno."); } finally { setWorking(false); } };
  const editShift = (item: ShiftTemplate) => { setEditingShiftId(item.id); setShift({ code: item.code, name: item.name, startTime: item.startTime, endTime: item.endTime, entryToleranceMinutes: item.entryToleranceMinutes, exitToleranceMinutes: item.exitToleranceMinutes, detectionWindowMinutes: item.detectionWindowMinutes, status: item.status }); };
  const toggleShift = async (item: ShiftTemplate) => { const activating = item.status !== "ACTIVO"; if (!await confirmAction(`¿Querés ${activating ? "activar" : "inactivar"} el turno “${item.name}”?`, { title: `${activating ? "Activar" : "Inactivar"} turno`, confirmLabel: activating ? "Activar" : "Inactivar", tone: activating ? "primary" : "danger" })) return; setWorking(true); setError(""); setNotice(""); try { await workforceApiService.updateShiftTemplate(item.id, { status: activating ? "ACTIVO" : "INACTIVO" }); setNotice(`Turno ${activating ? "activado" : "inactivado"} correctamente.`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo cambiar el estado del turno."); } finally { setWorking(false); } };
  const removeShift = async (item: ShiftTemplate) => { if (!await confirmAction(`Si el turno “${item.name}” ya fue utilizado, quedará inactivo para conservar las fichadas históricas. Si nunca se utilizó, se eliminará.`, { title: "Eliminar turno", confirmLabel: "Continuar", tone: "danger" })) return; setWorking(true); setError(""); setNotice(""); try { const result = await workforceApiService.removeShiftTemplate(item.id); setNotice(result.mode === "DELETED" ? "Turno eliminado correctamente." : `El turno tenía ${result.relatedWorkShifts} jornada${result.relatedWorkShifts === 1 ? "" : "s"} asociada${result.relatedWorkShifts === 1 ? "" : "s"}; quedó inactivo para conservar el historial.`); if (editingShiftId === item.id) resetShift(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo eliminar el turno."); } finally { setWorking(false); } };
  const submitRule = async (event: FormEvent) => { event.preventDefault(); setError(""); if (!selectedRuleEmployees.length) { setError("Seleccioná al menos una persona para crear la regla."); return; } setWorking(true); try { await workforceApiService.createDoubleHourRule({ ...rule, employeeIds: selectedRuleEmployees.map((employee) => employee.id), toDate: rule.toDate || null }); setRule({ ...rule, name: "", reason: "", employeeIds: [] }); setSelectedRuleEmployees([]); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo crear la regla."); } finally { setWorking(false); } };
  return <><PageHeader eyebrow="CONFIGURACIÓN" title="Turnos y horas especiales" description="Define horarios de referencia, tolerancias y días con cómputo multiplicado sin asignar turnos fijos a personas." />{error ? <div className="form-error">{error}</div> : null}{notice ? <div className="info-note">{notice}</div> : null}
    <Section title="Plantillas de turnos" subtitle="El fichador identifica automáticamente el turno más cercano; fuera del rango genera una alerta, no modifica horas.">
      <form className="settings-inline-form" onSubmit={submitShift}><label className="field"><span>Código</span><input required value={shift.code} onChange={(e)=>setShift({...shift,code:e.target.value})}/></label><label className="field"><span>Nombre</span><input required value={shift.name} onChange={(e)=>setShift({...shift,name:e.target.value})}/></label><label className="field"><span>Entrada</span><input type="time" required value={shift.startTime} onChange={(e)=>setShift({...shift,startTime:e.target.value})}/></label><label className="field"><span>Salida</span><input type="time" required value={shift.endTime} onChange={(e)=>setShift({...shift,endTime:e.target.value})}/></label><label className="field"><span>Tolerancia entrada</span><input type="number" min="0" max="180" value={shift.entryToleranceMinutes} onChange={(e)=>setShift({...shift,entryToleranceMinutes:Number(e.target.value)})}/></label><label className="field"><span>Tolerancia salida</span><input type="number" min="0" max="180" value={shift.exitToleranceMinutes} onChange={(e)=>setShift({...shift,exitToleranceMinutes:Number(e.target.value)})}/></label><Button variant="primary" icon={editingShiftId ? Pencil : Plus} disabled={working}>{editingShiftId ? "Guardar cambios" : "Agregar turno"}</Button>{editingShiftId ? <Button type="button" variant="subtle" icon={X} onClick={resetShift}>Cancelar</Button> : null}</form>
      {isLoading ? <LoadingState text="Cargando turnos..." /> : <><table><thead><tr><th>Código</th><th>Turno</th><th>Horario</th><th>Tolerancia entrada</th><th>Tolerancia salida</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{templates.map((item)=><tr key={item.id}><td><b>{item.code}</b></td><td>{item.name}</td><td>{item.startTime}–{item.endTime}</td><td>{item.entryToleranceMinutes} min</td><td>{item.exitToleranceMinutes} min</td><td><span className={`badge ${item.status === "ACTIVO" ? "success" : "neutral"}`}>{item.status === "ACTIVO" ? "Activo" : "Inactivo"}</span></td><td><div className="table-actions"><button type="button" className="table-icon-action" title="Editar turno" aria-label={`Editar ${item.name}`} onClick={()=>editShift(item)}><Pencil/><span>Editar</span></button><button type="button" className="table-icon-action" title={item.status === "ACTIVO" ? "Inactivar turno" : "Activar turno"} aria-label={`${item.status === "ACTIVO" ? "Inactivar" : "Activar"} ${item.name}`} onClick={()=>void toggleShift(item)}><Power/><span>{item.status === "ACTIVO" ? "Inactivar" : "Activar"}</span></button><button type="button" className="table-icon-action danger-link" title="Eliminar turno" aria-label={`Eliminar ${item.name}`} onClick={()=>void removeShift(item)}><Trash2/><span>Eliminar</span></button></div></td></tr>)}</tbody></table>{!templates.length?<div className="empty">Todavía no hay turnos configurados.</div>:null}</>}
    </Section>
    <Section title="Reglas de horas dobles" subtitle="La marcación real se conserva para auditoría; el total computable aplica el multiplicador configurado.">
      <form className="special-rule-form" onSubmit={submitRule}><div className="form-grid"><label className="field"><span>Nombre de la regla</span><input required value={rule.name} onChange={(e)=>setRule({...rule,name:e.target.value})}/></label><label className="field"><span>Repetición</span><select value={rule.recurrenceType} onChange={(e)=>setRule({...rule,recurrenceType:e.target.value as typeof rule.recurrenceType})}><option value="FECHA">Una fecha</option><option value="RANGO">Rango de fechas</option><option value="SEMANAL">Días semanales</option></select></label><label className="field"><span>Desde</span><input required type="date" value={rule.fromDate} onChange={(e)=>setRule({...rule,fromDate:e.target.value})}/></label><label className="field"><span>Hasta</span><input type="date" value={rule.toDate} onChange={(e)=>setRule({...rule,toDate:e.target.value})}/></label></div>{rule.recurrenceType==="SEMANAL"?<div className="weekday-picker">{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map((day,index)=><label key={day}><input type="checkbox" checked={rule.weekdays.includes(index)} onChange={(e)=>setRule({...rule,weekdays:e.target.checked?[...rule.weekdays,index]:rule.weekdays.filter((value)=>value!==index)})}/>{day}</label>)}</div>:null}<label className="field"><span>Motivo</span><input required value={rule.reason} onChange={(e)=>setRule({...rule,reason:e.target.value})}/></label><div className="rule-people-field"><span>Personas alcanzadas</span><EmployeeRemoteSelector selected={selectedRuleEmployees} multiple showStatusFilter wide={false} onChange={setSelectedRuleEmployees}/><small>Buscá y agregá todas las personas alcanzadas por la regla.</small></div><Button variant="primary" icon={Plus} disabled={working}>Crear regla</Button></form>
      {isLoading ? <LoadingState text="Cargando reglas de horas especiales..." /> : <><table><thead><tr><th>Regla</th><th>Aplicación</th><th>Período</th><th>Multiplicador</th><th>Personas</th><th>Motivo</th></tr></thead><tbody>{rules.map((item)=><tr key={item.id}><td><b>{item.name}</b></td><td>{item.recurrenceType}</td><td>{new Date(item.fromDate).toLocaleDateString("es-AR")}{item.toDate?` – ${new Date(item.toDate).toLocaleDateString("es-AR")}`:""}</td><td>x{Number(item.multiplier)}</td><td>{item.employees.length}</td><td>{item.reason}</td></tr>)}</tbody></table>{!rules.length?<div className="empty">Todavía no hay reglas de horas especiales.</div>:null}</>}
    </Section></>;
}
