import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, Pencil, Plus, Power, Trash2, X } from "lucide-react";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/ui/PageHeader";
import { Section } from "../components/ui/Section";
import { Button } from "../components/ui/Button";
import { LoadingState } from "../components/ui/LoadingState";
import { workforceApiService, type DoubleHourRule } from "../services/api/workforceApiService";
import type { Employee } from "../types";
import { confirmAction } from "../services/appDialog";
import { EmployeeRemoteSelector } from "../components/employees/EmployeeRemoteSelector";

export function WorkScheduleSettingsPage() {
  const [rules, setRules] = useState<DoubleHourRule[]>([]); const [selectedRuleEmployees, setSelectedRuleEmployees] = useState<Employee[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [working, setWorking] = useState(false); const [isLoading, setIsLoading] = useState(true);
  const [editingRuleId, setEditingRuleId] = useState<string>();
  const [rule, setRule] = useState({ name: "", recurrenceType: "FECHA" as "FECHA" | "RANGO" | "SEMANAL", fromDate: "", toDate: "", weekdays: [] as number[], multiplier: 2, employeeIds: [] as string[], reason: "" });
  const load = async () => { setIsLoading(true); try { const items = await workforceApiService.doubleHourRules(); setRules(items); } catch { setError("No se pudo cargar la configuración horaria."); } finally { setIsLoading(false); } };
  useEffect(() => { void load(); }, []);
  const resetRule = () => { setEditingRuleId(undefined); setRule({ name: "", recurrenceType: "FECHA", fromDate: "", toDate: "", weekdays: [], multiplier: 2, employeeIds: [], reason: "" }); setSelectedRuleEmployees([]); };
  const submitRule = async (event: FormEvent) => { event.preventDefault(); setError(""); setNotice(""); if (!selectedRuleEmployees.length) { setError("Seleccioná al menos una persona para guardar la regla."); return; } setWorking(true); try { const payload = { ...rule, employeeIds: selectedRuleEmployees.map((employee) => employee.id), toDate: rule.toDate || null }; if (editingRuleId) await workforceApiService.updateDoubleHourRule(editingRuleId, payload); else await workforceApiService.createDoubleHourRule(payload); setNotice(editingRuleId ? "Regla actualizada correctamente." : "Regla creada correctamente."); resetRule(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo guardar la regla."); } finally { setWorking(false); } };
  const editRule = (item: DoubleHourRule) => { setEditingRuleId(item.id); setRule({ name: item.name, recurrenceType: item.recurrenceType, fromDate: item.fromDate.slice(0,10), toDate: item.toDate?.slice(0,10) || "", weekdays: item.weekdays, multiplier: Number(item.multiplier), employeeIds: item.employees.map(({ employee }) => employee.id), reason: item.reason }); setSelectedRuleEmployees(item.employees.map(({ employee }) => employee as Employee)); document.getElementById("double-hour-rule-form")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const toggleRule = async (item: DoubleHourRule) => { const activating = item.status !== "ACTIVO"; if (!await confirmAction(`¿Querés ${activating ? "activar" : "inactivar"} la regla “${item.name}”?`, { title: `${activating ? "Activar" : "Inactivar"} regla`, confirmLabel: activating ? "Activar" : "Inactivar", tone: activating ? "primary" : "danger" })) return; setWorking(true); setError(""); setNotice(""); try { await workforceApiService.updateDoubleHourRule(item.id, { status: activating ? "ACTIVO" : "INACTIVO" }); setNotice(`Regla ${activating ? "activada" : "inactivada"} correctamente.`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo cambiar el estado de la regla."); } finally { setWorking(false); } };
  const removeRule = async (item: DoubleHourRule) => { if (!await confirmAction(`Si la regla “${item.name}” ya comenzó, quedará inactiva para conservar la trazabilidad. Si todavía es futura, se eliminará.`, { title: "Eliminar regla", confirmLabel: "Continuar", tone: "danger" })) return; setWorking(true); setError(""); setNotice(""); try { const result = await workforceApiService.removeDoubleHourRule(item.id); setNotice(result.mode === "DELETED" ? "Regla eliminada correctamente." : "La regla ya había comenzado y quedó inactiva para preservar los cálculos históricos."); if (editingRuleId === item.id) resetRule(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo eliminar la regla."); } finally { setWorking(false); } };
  return <><PageHeader eyebrow="CONFIGURACIÓN" title="Horas especiales" description="Días y rangos con cómputo multiplicado, independientes de los turnos de referencia." />{error ? <div className="form-error">{error}</div> : null}{notice ? <div className="info-note">{notice}</div> : null}
    <Section className="schedule-settings-section" title="Turnos" subtitle="La gestión de turnos, tolerancias y empleados asociados se mudó a su propio módulo.">
      <Link to="/configuracion/turnos" className="button primary">Ir a Turnos <ArrowRight size={16} /></Link>
    </Section>
    <Section className="schedule-settings-section" title="Reglas de horas dobles" subtitle="La marcación real se conserva para auditoría; el total computable aplica el multiplicador configurado.">
      <form id="double-hour-rule-form" className="special-rule-form" onSubmit={submitRule}><div className="form-grid"><label className="field"><span>Nombre de la regla</span><input required value={rule.name} onChange={(e)=>setRule({...rule,name:e.target.value})}/></label><label className="field"><span>Repetición</span><select value={rule.recurrenceType} onChange={(e)=>setRule({...rule,recurrenceType:e.target.value as typeof rule.recurrenceType})}><option value="FECHA">Una fecha</option><option value="RANGO">Rango de fechas</option><option value="SEMANAL">Días semanales</option></select></label><label className="field"><span>Desde</span><input required type="date" value={rule.fromDate} onChange={(e)=>setRule({...rule,fromDate:e.target.value})}/></label><label className="field"><span>Hasta</span><input type="date" value={rule.toDate} onChange={(e)=>setRule({...rule,toDate:e.target.value})}/></label></div>{rule.recurrenceType==="SEMANAL"?<div className="weekday-picker">{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map((day,index)=><label key={day}><input type="checkbox" checked={rule.weekdays.includes(index)} onChange={(e)=>setRule({...rule,weekdays:e.target.checked?[...rule.weekdays,index]:rule.weekdays.filter((value)=>value!==index)})}/>{day}</label>)}</div>:null}<label className="field"><span>Motivo</span><input required value={rule.reason} onChange={(e)=>setRule({...rule,reason:e.target.value})}/></label><div className="rule-people-field"><span>Personas alcanzadas</span><EmployeeRemoteSelector selected={selectedRuleEmployees} multiple showStatusFilter wide={false} onChange={setSelectedRuleEmployees}/><small>Buscá y agregá todas las personas alcanzadas por la regla.</small></div><div className="rule-form-actions"><Button variant="primary" icon={editingRuleId ? Pencil : Plus} disabled={working}>{editingRuleId ? "Guardar cambios" : "Crear regla"}</Button>{editingRuleId ? <Button type="button" variant="subtle" icon={X} onClick={resetRule}>Cancelar edición</Button> : null}</div></form>
      {isLoading ? <LoadingState text="Cargando reglas de horas especiales..." /> : <><div className="settings-table-scroll"><table><thead><tr><th>Regla</th><th>Aplicación</th><th>Período</th><th>Multiplicador</th><th>Personas</th><th>Motivo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rules.map((item)=><tr key={item.id}><td><b>{item.name}</b></td><td>{item.recurrenceType}</td><td>{new Date(item.fromDate).toLocaleDateString("es-AR")}{item.toDate?` – ${new Date(item.toDate).toLocaleDateString("es-AR")}`:""}</td><td>x{Number(item.multiplier)}</td><td>{item.employees.length}</td><td>{item.reason}</td><td><span className={`badge ${item.status === "ACTIVO" ? "success" : "neutral"}`}>{item.status === "ACTIVO" ? "Activa" : "Inactiva"}</span></td><td><div className="table-actions"><button type="button" className="table-icon-action" title="Editar regla" aria-label={`Editar ${item.name}`} onClick={()=>editRule(item)}><Pencil/><span>Editar</span></button><button type="button" className="table-icon-action" title={item.status === "ACTIVO" ? "Inactivar regla" : "Activar regla"} aria-label={`${item.status === "ACTIVO" ? "Inactivar" : "Activar"} ${item.name}`} onClick={()=>void toggleRule(item)}><Power/><span>{item.status === "ACTIVO" ? "Inactivar" : "Activar"}</span></button><button type="button" className="table-icon-action danger-link" title="Eliminar regla" aria-label={`Eliminar ${item.name}`} onClick={()=>void removeRule(item)}><Trash2/><span>Eliminar</span></button></div></td></tr>)}</tbody></table></div>{!rules.length?<div className="empty">Todavía no hay reglas de horas especiales.</div>:null}</>}
    </Section></>;
}
