import { useEffect, useState, type FormEvent } from "react";
import { Plus } from "lucide-react";
import { PageHeader } from "../components/ui/PageHeader";
import { Section } from "../components/ui/Section";
import { Button } from "../components/ui/Button";
import { employeeApiService } from "../services/api/employeeApiService";
import { workforceApiService, type DoubleHourRule, type ShiftTemplate } from "../services/api/workforceApiService";
import type { Employee } from "../types";

export function WorkScheduleSettingsPage() {
  const [templates, setTemplates] = useState<ShiftTemplate[]>([]); const [rules, setRules] = useState<DoubleHourRule[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [error, setError] = useState(""); const [working, setWorking] = useState(false);
  const [shift, setShift] = useState({ code: "", name: "", startTime: "07:00", endTime: "15:00", entryToleranceMinutes: 10, exitToleranceMinutes: 20, detectionWindowMinutes: 180, status: "ACTIVO" });
  const [rule, setRule] = useState({ name: "", recurrenceType: "FECHA" as "FECHA" | "RANGO" | "SEMANAL", fromDate: "", toDate: "", weekdays: [] as number[], multiplier: 2, employeeIds: [] as string[], reason: "" });
  const load = async () => { try { const [a,b,c] = await Promise.all([workforceApiService.shiftTemplates(), workforceApiService.doubleHourRules(), employeeApiService.getOptions({ take: 1000 })]); setTemplates(a); setRules(b); setEmployees(c.items); } catch { setError("No se pudo cargar la configuración horaria."); } };
  useEffect(() => { void load(); }, []);
  const submitShift = async (event: FormEvent) => { event.preventDefault(); setWorking(true); setError(""); try { await workforceApiService.createShiftTemplate(shift); setShift({ ...shift, code: "", name: "" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo crear el turno."); } finally { setWorking(false); } };
  const submitRule = async (event: FormEvent) => { event.preventDefault(); setWorking(true); setError(""); try { await workforceApiService.createDoubleHourRule({ ...rule, toDate: rule.toDate || null }); setRule({ ...rule, name: "", reason: "", employeeIds: [] }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo crear la regla."); } finally { setWorking(false); } };
  return <><PageHeader eyebrow="CONFIGURACIÓN" title="Turnos y horas especiales" description="Define horarios de referencia, tolerancias y días con cómputo multiplicado sin asignar turnos fijos a personas." />{error ? <div className="form-error">{error}</div> : null}
    <Section title="Plantillas de turnos" subtitle="El fichador identifica automáticamente el turno más cercano; fuera del rango genera una alerta, no modifica horas.">
      <form className="settings-inline-form" onSubmit={submitShift}><label className="field"><span>Código</span><input required value={shift.code} onChange={(e)=>setShift({...shift,code:e.target.value})}/></label><label className="field"><span>Nombre</span><input required value={shift.name} onChange={(e)=>setShift({...shift,name:e.target.value})}/></label><label className="field"><span>Entrada</span><input type="time" required value={shift.startTime} onChange={(e)=>setShift({...shift,startTime:e.target.value})}/></label><label className="field"><span>Salida</span><input type="time" required value={shift.endTime} onChange={(e)=>setShift({...shift,endTime:e.target.value})}/></label><label className="field"><span>Tolerancia entrada</span><input type="number" min="0" max="180" value={shift.entryToleranceMinutes} onChange={(e)=>setShift({...shift,entryToleranceMinutes:Number(e.target.value)})}/></label><label className="field"><span>Tolerancia salida</span><input type="number" min="0" max="180" value={shift.exitToleranceMinutes} onChange={(e)=>setShift({...shift,exitToleranceMinutes:Number(e.target.value)})}/></label><Button variant="primary" icon={Plus} disabled={working}>Agregar turno</Button></form>
      <table><thead><tr><th>Código</th><th>Turno</th><th>Horario</th><th>Tolerancia entrada</th><th>Tolerancia salida</th><th>Estado</th></tr></thead><tbody>{templates.map((item)=><tr key={item.id}><td><b>{item.code}</b></td><td>{item.name}</td><td>{item.startTime}–{item.endTime}</td><td>{item.entryToleranceMinutes} min</td><td>{item.exitToleranceMinutes} min</td><td><span className="badge success">Activo</span></td></tr>)}</tbody></table>{!templates.length?<div className="empty">Todavía no hay turnos configurados.</div>:null}
    </Section>
    <Section title="Reglas de horas dobles" subtitle="La marcación real se conserva para auditoría; el total computable aplica el multiplicador configurado.">
      <form className="special-rule-form" onSubmit={submitRule}><div className="form-grid"><label className="field"><span>Nombre de la regla</span><input required value={rule.name} onChange={(e)=>setRule({...rule,name:e.target.value})}/></label><label className="field"><span>Repetición</span><select value={rule.recurrenceType} onChange={(e)=>setRule({...rule,recurrenceType:e.target.value as typeof rule.recurrenceType})}><option value="FECHA">Una fecha</option><option value="RANGO">Rango de fechas</option><option value="SEMANAL">Días semanales</option></select></label><label className="field"><span>Desde</span><input required type="date" value={rule.fromDate} onChange={(e)=>setRule({...rule,fromDate:e.target.value})}/></label><label className="field"><span>Hasta</span><input type="date" value={rule.toDate} onChange={(e)=>setRule({...rule,toDate:e.target.value})}/></label></div>{rule.recurrenceType==="SEMANAL"?<div className="weekday-picker">{["Dom","Lun","Mar","Mié","Jue","Vie","Sáb"].map((day,index)=><label key={day}><input type="checkbox" checked={rule.weekdays.includes(index)} onChange={(e)=>setRule({...rule,weekdays:e.target.checked?[...rule.weekdays,index]:rule.weekdays.filter((value)=>value!==index)})}/>{day}</label>)}</div>:null}<label className="field"><span>Motivo</span><input required value={rule.reason} onChange={(e)=>setRule({...rule,reason:e.target.value})}/></label><label className="field"><span>Personas alcanzadas</span><select multiple required value={rule.employeeIds} onChange={(e)=>setRule({...rule,employeeIds:Array.from(e.target.selectedOptions,(option)=>option.value)})}>{employees.map((employee)=><option key={employee.id} value={employee.id}>{employee.legajo} · {employee.lastName}, {employee.firstName}</option>)}</select><small>Usá Ctrl/Cmd para seleccionar varias personas.</small></label><Button variant="primary" icon={Plus} disabled={working}>Crear regla</Button></form>
      <table><thead><tr><th>Regla</th><th>Aplicación</th><th>Período</th><th>Multiplicador</th><th>Personas</th><th>Motivo</th></tr></thead><tbody>{rules.map((item)=><tr key={item.id}><td><b>{item.name}</b></td><td>{item.recurrenceType}</td><td>{new Date(item.fromDate).toLocaleDateString("es-AR")}{item.toDate?` – ${new Date(item.toDate).toLocaleDateString("es-AR")}`:""}</td><td>x{Number(item.multiplier)}</td><td>{item.employees.length}</td><td>{item.reason}</td></tr>)}</tbody></table>{!rules.length?<div className="empty">Todavía no hay reglas de horas especiales.</div>:null}
    </Section></>;
}
